// Code generated by ent, DO NOT EDIT.

package polloption

import (
	"pollapp/backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PollOption {
	return predicate.PollOption(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PollOption {
	return predicate.PollOption(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PollOption {
	return predicate.PollOption(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PollOption {
	return predicate.PollOption(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PollOption {
	return predicate.PollOption(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PollOption {
	return predicate.PollOption(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PollOption {
	return predicate.PollOption(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PollOption {
	return predicate.PollOption(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PollOption {
	return predicate.PollOption(sql.FieldLTE(FieldID, id))
}

// PollID applies equality check predicate on the "poll_id" field. It's identical to PollIDEQ.
func PollID(v int) predicate.PollOption {
	return predicate.PollOption(sql.FieldEQ(FieldPollID, v))
}

// OptionText applies equality check predicate on the "option_text" field. It's identical to OptionTextEQ.
func OptionText(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldEQ(FieldOptionText, v))
}

// Order applies equality check predicate on the "order" field. It's identical to OrderEQ.
func Order(v int) predicate.PollOption {
	return predicate.PollOption(sql.FieldEQ(FieldOrder, v))
}

// PollIDEQ applies the EQ predicate on the "poll_id" field.
func PollIDEQ(v int) predicate.PollOption {
	return predicate.PollOption(sql.FieldEQ(FieldPollID, v))
}

// PollIDNEQ applies the NEQ predicate on the "poll_id" field.
func PollIDNEQ(v int) predicate.PollOption {
	return predicate.PollOption(sql.FieldNEQ(FieldPollID, v))
}

// PollIDIn applies the In predicate on the "poll_id" field.
func PollIDIn(vs ...int) predicate.PollOption {
	return predicate.PollOption(sql.FieldIn(FieldPollID, vs...))
}

// PollIDNotIn applies the NotIn predicate on the "poll_id" field.
func PollIDNotIn(vs ...int) predicate.PollOption {
	return predicate.PollOption(sql.FieldNotIn(FieldPollID, vs...))
}

// OptionTextEQ applies the EQ predicate on the "option_text" field.
func OptionTextEQ(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldEQ(FieldOptionText, v))
}

// OptionTextNEQ applies the NEQ predicate on the "option_text" field.
func OptionTextNEQ(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldNEQ(FieldOptionText, v))
}

// OptionTextIn applies the In predicate on the "option_text" field.
func OptionTextIn(vs ...string) predicate.PollOption {
	return predicate.PollOption(sql.FieldIn(FieldOptionText, vs...))
}

// OptionTextNotIn applies the NotIn predicate on the "option_text" field.
func OptionTextNotIn(vs ...string) predicate.PollOption {
	return predicate.PollOption(sql.FieldNotIn(FieldOptionText, vs...))
}

// OptionTextGT applies the GT predicate on the "option_text" field.
func OptionTextGT(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldGT(FieldOptionText, v))
}

// OptionTextGTE applies the GTE predicate on the "option_text" field.
func OptionTextGTE(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldGTE(FieldOptionText, v))
}

// OptionTextLT applies the LT predicate on the "option_text" field.
func OptionTextLT(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldLT(FieldOptionText, v))
}

// OptionTextLTE applies the LTE predicate on the "option_text" field.
func OptionTextLTE(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldLTE(FieldOptionText, v))
}

// OptionTextContains applies the Contains predicate on the "option_text" field.
func OptionTextContains(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldContains(FieldOptionText, v))
}

// OptionTextHasPrefix applies the HasPrefix predicate on the "option_text" field.
func OptionTextHasPrefix(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldHasPrefix(FieldOptionText, v))
}

// OptionTextHasSuffix applies the HasSuffix predicate on the "option_text" field.
func OptionTextHasSuffix(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldHasSuffix(FieldOptionText, v))
}

// OptionTextEqualFold applies the EqualFold predicate on the "option_text" field.
func OptionTextEqualFold(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldEqualFold(FieldOptionText, v))
}

// OptionTextContainsFold applies the ContainsFold predicate on the "option_text" field.
func OptionTextContainsFold(v string) predicate.PollOption {
	return predicate.PollOption(sql.FieldContainsFold(FieldOptionText, v))
}

// OrderEQ applies the EQ predicate on the "order" field.
func OrderEQ(v int) predicate.PollOption {
	return predicate.PollOption(sql.FieldEQ(FieldOrder, v))
}

// OrderNEQ applies the NEQ predicate on the "order" field.
func OrderNEQ(v int) predicate.PollOption {
	return predicate.PollOption(sql.FieldNEQ(FieldOrder, v))
}

// OrderIn applies the In predicate on the "order" field.
func OrderIn(vs ...int) predicate.PollOption {
	return predicate.PollOption(sql.FieldIn(FieldOrder, vs...))
}

// OrderNotIn applies the NotIn predicate on the "order" field.
func OrderNotIn(vs ...int) predicate.PollOption {
	return predicate.PollOption(sql.FieldNotIn(FieldOrder, vs...))
}

// OrderGT applies the GT predicate on the "order" field.
func OrderGT(v int) predicate.PollOption {
	return predicate.PollOption(sql.FieldGT(FieldOrder, v))
}

// OrderGTE applies the GTE predicate on the "order" field.
func OrderGTE(v int) predicate.PollOption {
	return predicate.PollOption(sql.FieldGTE(FieldOrder, v))
}

// OrderLT applies the LT predicate on the "order" field.
func OrderLT(v int) predicate.PollOption {
	return predicate.PollOption(sql.FieldLT(FieldOrder, v))
}

// OrderLTE applies the LTE predicate on the "order" field.
func OrderLTE(v int) predicate.PollOption {
	return predicate.PollOption(sql.FieldLTE(FieldOrder, v))
}

// HasPoll applies the HasEdge predicate on the "poll" edge.
func HasPoll() predicate.PollOption {
	return predicate.PollOption(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, PollTable, PollColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPollWith applies the HasEdge predicate on the "poll" edge with a given conditions (other predicates).
func HasPollWith(preds ...predicate.Poll) predicate.PollOption {
	return predicate.PollOption(func(s *sql.Selector) {
		step := newPollStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasVotes applies the HasEdge predicate on the "votes" edge.
func HasVotes() predicate.PollOption {
	return predicate.PollOption(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, VotesTable, VotesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVotesWith applies the HasEdge predicate on the "votes" edge with a given conditions (other predicates).
func HasVotesWith(preds ...predicate.Vote) predicate.PollOption {
	return predicate.PollOption(func(s *sql.Selector) {
		step := newVotesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PollOption) predicate.PollOption {
	return predicate.PollOption(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PollOption) predicate.PollOption {
	return predicate.PollOption(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PollOption) predicate.PollOption {
	return predicate.PollOption(sql.NotPredicates(p))
}
