// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"pollapp/backend/ent/poll"
	"pollapp/backend/ent/polloption"
	"pollapp/backend/ent/vote"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PollOptionCreate is the builder for creating a PollOption entity.
type PollOptionCreate struct {
	config
	mutation *PollOptionMutation
	hooks    []Hook
}

// SetPollID sets the "poll_id" field.
func (_c *PollOptionCreate) SetPollID(v int) *PollOptionCreate {
	_c.mutation.SetPollID(v)
	return _c
}

// SetOptionText sets the "option_text" field.
func (_c *PollOptionCreate) SetOptionText(v string) *PollOptionCreate {
	_c.mutation.SetOptionText(v)
	return _c
}

// SetOrder sets the "order" field.
func (_c *PollOptionCreate) SetOrder(v int) *PollOptionCreate {
	_c.mutation.SetOrder(v)
	return _c
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_c *PollOptionCreate) SetNillableOrder(v *int) *PollOptionCreate {
	if v != nil {
		_c.SetOrder(*v)
	}
	return _c
}

// SetPoll sets the "poll" edge to the Poll entity.
func (_c *PollOptionCreate) SetPoll(v *Poll) *PollOptionCreate {
	return _c.SetPollID(v.ID)
}

// AddVoteIDs adds the "votes" edge to the Vote entity by IDs.
func (_c *PollOptionCreate) AddVoteIDs(ids ...int) *PollOptionCreate {
	_c.mutation.AddVoteIDs(ids...)
	return _c
}

// AddVotes adds the "votes" edges to the Vote entity.
func (_c *PollOptionCreate) AddVotes(v ...*Vote) *PollOptionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVoteIDs(ids...)
}

// Mutation returns the PollOptionMutation object of the builder.
func (_c *PollOptionCreate) Mutation() *PollOptionMutation {
	return _c.mutation
}

// Save creates the PollOption in the database.
func (_c *PollOptionCreate) Save(ctx context.Context) (*PollOption, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PollOptionCreate) SaveX(ctx context.Context) *PollOption {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PollOptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PollOptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PollOptionCreate) defaults() {
	if _, ok := _c.mutation.Order(); !ok {
		v := polloption.DefaultOrder
		_c.mutation.SetOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PollOptionCreate) check() error {
	if _, ok := _c.mutation.PollID(); !ok {
		return &ValidationError{Name: "poll_id", err: errors.New(`ent: missing required field "PollOption.poll_id"`)}
	}
	if _, ok := _c.mutation.OptionText(); !ok {
		return &ValidationError{Name: "option_text", err: errors.New(`ent: missing required field "PollOption.option_text"`)}
	}
	if _, ok := _c.mutation.Order(); !ok {
		return &ValidationError{Name: "order", err: errors.New(`ent: missing required field "PollOption.order"`)}
	}
	if len(_c.mutation.PollIDs()) == 0 {
		return &ValidationError{Name: "poll", err: errors.New(`ent: missing required edge "PollOption.poll"`)}
	}
	return nil
}

func (_c *PollOptionCreate) sqlSave(ctx context.Context) (*PollOption, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PollOptionCreate) createSpec() (*PollOption, *sqlgraph.CreateSpec) {
	var (
		_node = &PollOption{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(polloption.Table, sqlgraph.NewFieldSpec(polloption.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.OptionText(); ok {
		_spec.SetField(polloption.FieldOptionText, field.TypeString, value)
		_node.OptionText = value
	}
	if value, ok := _c.mutation.Order(); ok {
		_spec.SetField(polloption.FieldOrder, field.TypeInt, value)
		_node.Order = value
	}
	if nodes := _c.mutation.PollIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   polloption.PollTable,
			Columns: []string{polloption.PollColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(poll.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PollID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VotesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   polloption.VotesTable,
			Columns: []string{polloption.VotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vote.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PollOptionCreateBulk is the builder for creating many PollOption entities in bulk.
type PollOptionCreateBulk struct {
	config
	err      error
	builders []*PollOptionCreate
}

// Save creates the PollOption entities in the database.
func (_c *PollOptionCreateBulk) Save(ctx context.Context) ([]*PollOption, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PollOption, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PollOptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PollOptionCreateBulk) SaveX(ctx context.Context) []*PollOption {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PollOptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PollOptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
