// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"pollapp/backend/ent/poll"
	"pollapp/backend/ent/polloption"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PollOption is the model entity for the PollOption schema.
type PollOption struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PollID holds the value of the "poll_id" field.
	PollID int `json:"poll_id,omitempty"`
	// OptionText holds the value of the "option_text" field.
	OptionText string `json:"option_text,omitempty"`
	// Order holds the value of the "order" field.
	Order int `json:"order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PollOptionQuery when eager-loading is set.
	Edges        PollOptionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PollOptionEdges holds the relations/edges for other nodes in the graph.
type PollOptionEdges struct {
	// Poll holds the value of the poll edge.
	Poll *Poll `json:"poll,omitempty"`
	// Votes holds the value of the votes edge.
	Votes []*Vote `json:"votes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PollOrErr returns the Poll value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PollOptionEdges) PollOrErr() (*Poll, error) {
	if e.Poll != nil {
		return e.Poll, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: poll.Label}
	}
	return nil, &NotLoadedError{edge: "poll"}
}

// VotesOrErr returns the Votes value or an error if the edge
// was not loaded in eager-loading.
func (e PollOptionEdges) VotesOrErr() ([]*Vote, error) {
	if e.loadedTypes[1] {
		return e.Votes, nil
	}
	return nil, &NotLoadedError{edge: "votes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PollOption) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case polloption.FieldID, polloption.FieldPollID, polloption.FieldOrder:
			values[i] = new(sql.NullInt64)
		case polloption.FieldOptionText:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PollOption fields.
func (_m *PollOption) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case polloption.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case polloption.FieldPollID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field poll_id", values[i])
			} else if value.Valid {
				_m.PollID = int(value.Int64)
			}
		case polloption.FieldOptionText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field option_text", values[i])
			} else if value.Valid {
				_m.OptionText = value.String
			}
		case polloption.FieldOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order", values[i])
			} else if value.Valid {
				_m.Order = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PollOption.
// This includes values selected through modifiers, order, etc.
func (_m *PollOption) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPoll queries the "poll" edge of the PollOption entity.
func (_m *PollOption) QueryPoll() *PollQuery {
	return NewPollOptionClient(_m.config).QueryPoll(_m)
}

// QueryVotes queries the "votes" edge of the PollOption entity.
func (_m *PollOption) QueryVotes() *VoteQuery {
	return NewPollOptionClient(_m.config).QueryVotes(_m)
}

// Update returns a builder for updating this PollOption.
// Note that you need to call PollOption.Unwrap() before calling this method if this PollOption
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PollOption) Update() *PollOptionUpdateOne {
	return NewPollOptionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PollOption entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PollOption) Unwrap() *PollOption {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PollOption is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PollOption) String() string {
	var builder strings.Builder
	builder.WriteString("PollOption(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("poll_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PollID))
	builder.WriteString(", ")
	builder.WriteString("option_text=")
	builder.WriteString(_m.OptionText)
	builder.WriteString(", ")
	builder.WriteString("order=")
	builder.WriteString(fmt.Sprintf("%v", _m.Order))
	builder.WriteByte(')')
	return builder.String()
}

// PollOptions is a parsable slice of PollOption.
type PollOptions []*PollOption
