// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"pollapp/backend/ent/poll"
	"pollapp/backend/ent/polloption"
	"pollapp/backend/ent/user"
	"pollapp/backend/ent/vote"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Vote is the model entity for the Vote schema.
type Vote struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PollID holds the value of the "poll_id" field.
	PollID int `json:"poll_id,omitempty"`
	// PollOptionID holds the value of the "poll_option_id" field.
	PollOptionID int `json:"poll_option_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VoteQuery when eager-loading is set.
	Edges        VoteEdges `json:"edges"`
	selectValues sql.SelectValues
}

// VoteEdges holds the relations/edges for other nodes in the graph.
type VoteEdges struct {
	// Poll holds the value of the poll edge.
	Poll *Poll `json:"poll,omitempty"`
	// PollOption holds the value of the poll_option edge.
	PollOption *PollOption `json:"poll_option,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// PollOrErr returns the Poll value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VoteEdges) PollOrErr() (*Poll, error) {
	if e.Poll != nil {
		return e.Poll, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: poll.Label}
	}
	return nil, &NotLoadedError{edge: "poll"}
}

// PollOptionOrErr returns the PollOption value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VoteEdges) PollOptionOrErr() (*PollOption, error) {
	if e.PollOption != nil {
		return e.PollOption, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: polloption.Label}
	}
	return nil, &NotLoadedError{edge: "poll_option"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VoteEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Vote) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case vote.FieldID, vote.FieldPollID, vote.FieldPollOptionID, vote.FieldUserID:
			values[i] = new(sql.NullInt64)
		case vote.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Vote fields.
func (_m *Vote) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case vote.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case vote.FieldPollID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field poll_id", values[i])
			} else if value.Valid {
				_m.PollID = int(value.Int64)
			}
		case vote.FieldPollOptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field poll_option_id", values[i])
			} else if value.Valid {
				_m.PollOptionID = int(value.Int64)
			}
		case vote.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case vote.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Vote.
// This includes values selected through modifiers, order, etc.
func (_m *Vote) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPoll queries the "poll" edge of the Vote entity.
func (_m *Vote) QueryPoll() *PollQuery {
	return NewVoteClient(_m.config).QueryPoll(_m)
}

// QueryPollOption queries the "poll_option" edge of the Vote entity.
func (_m *Vote) QueryPollOption() *PollOptionQuery {
	return NewVoteClient(_m.config).QueryPollOption(_m)
}

// QueryUser queries the "user" edge of the Vote entity.
func (_m *Vote) QueryUser() *UserQuery {
	return NewVoteClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this Vote.
// Note that you need to call Vote.Unwrap() before calling this method if this Vote
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Vote) Update() *VoteUpdateOne {
	return NewVoteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Vote entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Vote) Unwrap() *Vote {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Vote is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Vote) String() string {
	var builder strings.Builder
	builder.WriteString("Vote(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("poll_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PollID))
	builder.WriteString(", ")
	builder.WriteString("poll_option_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PollOptionID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Votes is a parsable slice of Vote.
type Votes []*Vote
